### ISSUE TITLE
Base command does not support numbers outside of the signed 32bit integer limit.

### ISSUE THREAD

**Issue by alxndr2000** [RedstoneTools/redstonetools#109]
``` /base 10 2147483648 2 ``` returns "Input number does not match the specified base" (2147483648 = 2^31)
``` /base 12 4bb2308a8 10 ```Returns the same thing 4bb2308a8 is 2^31 in base 12

This should return a more descriptive error letting the user know the inputted value is too large
It would also be nice to change the data type used

**Comment by Matthias1590** [comment]
Using a BigInteger instead of an Integer should fix this

**Comment by Matthias1590** [comment]
Solved by #112

**Comment by MiranCZ** [comment]
Doesnt using long just move the problem 32 more bits?
