### ISSUE TITLE
The auto dust feature does not update the dust placed diagonally.

### ISSUE THREAD

**Issue by alxndr2000** [RedstoneTools/redstonetools#111]
See attached screenshot
![image](https://user-images.githubusercontent.com/7605502/224084723-794f3f5c-5b4e-411a-8ad3-4efd802bcc6a.png)

**Comment by Matthias1590** [comment]
I don't think it updates dust at all

**Comment by MiranCZ** [comment]
I think this is just a visual glitch.

**Comment by Ninty9** [comment]
Can confirm that sending any sort of redstone power through it will fix it, this is purely visual.

**Comment by Matthias1590** [comment]
still might be nice to fix this, does anyone happen to know of an easy way to do so?

**Comment by MiranCZ** [comment]
You could try something like spawning the redstone powered, but idk

**Comment by Ninty9** [comment]
that would mean that you also trigger anything that's connected to that line.
someone mentioned something about trying to re render locked repeaters after //update, so whatever that ends up being _might_ work for this visual bug, but considering it goes away the instant you either power it or connect anything to it i'm not sure if it's even worth the effort.

**Comment by Matthias1590** [comment]
Resolved by #150
