### ISSUE TITLE
Add worldedit as a dependency as opposed to a suggestion

### ISSUE THREAD

**Issue by Matthias1590** [RedstoneTools/redstonetools#137]
Might already be fixed but just to be sure I created this issue

**Comment by RUGMJ** [comment]
Why? Not all features use worldedit and for people who dont use WE they wont want or need the mod installed

**Comment by Matthias1590** [comment]
> Why? Not all features use worldedit and for people who dont use WE they wont want or need the mod installed

Except they do, the mod crashes if you dont have worldedit installed

**Comment by Matthias1590** [comment]
If we can find a way to let users run the mod without worldedit installed without crashing like RUGMJ said then that'd be better. Haven't been able to figure out a way to do that though

**Comment by Matthias1590** [comment]
> If we can find a way to let users run the mod without worldedit installed without crashing like RUGMJ said then that'd be better. Haven't been able to figure out a way to do that though

This should probably be a separate issue and this one is done so im closing this one
