### ISSUE TITLE
Add confirmation screen to MacroEditScreen

### ISSUE THREAD

**Issue by MiranCZ** [RedstoneTools/redstonetools#157]
It happened to me quite a lot when I was testing, I instinctively pressed escape when editing a macro and the changes got cancelled.
 I think adding some kind of confirmation screen that you are about to cancel unsaved changes might be good addition.

**Comment by RUGMJ** [comment]
What about just saving on escape. I think that would be cleaner

**Comment by RUGMJ** [comment]
True but it would also mean making adjustments to macro quicker because you can just use the keyboard, if escape discarded changes then it would mean you would have to use the mouse to click save

**Comment by RUGMJ** [comment]
There could also be a discard button added which would discard the changes and leave the menu

**Comment by Matthias1590** [comment]
I don't think we need a button just to save, what we have rn works fine
